name: Deploy
on:
    push:
        branches: [main]
jobs:
  terraform_apply:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Auth GCloud
          uses: 'google-github-actions/auth@v2.1.2'
          with:
            credentials_json: ${{ secrets.CREDENTIALS }}
            create_credentials_file: true

        - name: Set up GCloud
          uses: "google-github-actions/setup-gcloud@v1"

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Terraform init with upgrade
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS }}
          run: terraform init -backend-config="bucket=bucket-action" -upgrade
        
        - name: Terraform validate
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS }}
          run: terraform validate

        - name: Terraform plan
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS }}
          run: terraform plan

        - name: Terraform Apply
          env:
            GOOGLE_CREDENTIALS: ${{ secrets.CREDENTIALS }}
          run: |
            terraform destroy -auto-approve -var="project_id=orderly-tech-challenge" -var="region=us-central1" -var="zone=us-central1-c"

        # - name: Database Data
        #   run: terraform output db_info
